apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-info-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: users-info-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80